"""add contacts

Revision ID: 4da6895ce357
Revises: a56eb26abcfa
Create Date: 2026-05-19 04:43:00.856865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da6895ce357'
down_revision: Union[str, Sequence[str], None] = 'a56eb26abcfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('contacts', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'contacts')
    # ### end Alembic commands ###
